version: '3.7'

services:
  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/test-server/src
      - /srv/app/node_modules
    command: npm run dev

  client:
    build: ./client
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/test-client/src
      - ./client/public:/srv/app/test-client/public
      - /srv/app/node_modules
    links:
      - server
    command: npm run start